apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pzcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pzcl
    app.kubernetes.io/part-of: load-app-ccfa722b-8cc6-4e14-8674-e780516e3b85
  name: devfile-sample-pzcl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pzcl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pzcl
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-77-tenant/load-app-ccfa722b-8cc6-4e14-8674-e780516e3b85/devfile-sample-pzcl@sha256:33fda06b10d969ae3c9d2b2e9549ad4e71a826aa5681184a6b2ee10bb6f0fd8e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
