apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pzcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pzcl
    app.kubernetes.io/part-of: load-app-ccfa722b-8cc6-4e14-8674-e780516e3b85
  name: devfile-sample-pzcl
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-pzcl
status:
  loadBalancer: {}
